version: 1.1.0.{build}-{branch}

skip_non_tags: true

image: Visual Studio 2015

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

environment:
  COVERALLS_REPO_TOKEN:
    secure: kv0pn7M34ca0KP8NlRekeusUa+Uj325NlZOhMNnK1EPW2cudunWXbZ/igtRouTnC

before_build:
  - nuget restore "SSRSMigrate\SSRSMigrate.sln"

build:
  project: SSRSMigrate\SSRSMigrate.sln
  verbosity: minimal

test:
  assemblies:
    except:
      - SSRSMigrate.IntegrationTests.dll

after_test:
  -cmd:nuget install NUnit.ConsoleRunner -OutputDirectory packages -Version 3.9.0
  -cmd:nuget install OpenCover -OutputDirectory packages -Version 4.6.519
  -cmd:dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
  -cmd:.\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:".\packages\NUnit.ConsoleRunner.3.9.0\tools\nunit3-console.exe" -targetargs:"/domain:single C:\projects\ssrsmigrate\SSRSMigrate\SSRSMigrate.Tests\bin\Debug\SSRSMigrate.Tests.dll" -output:coverage.xml
  -cmd:.\tools\csmacnz.coveralls.exe --opencover -i coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
